"""usage_daily

Revision ID: 63ba75848200
Revises: bf751ea53a90
Create Date: 2026-06-06 13:56:40.188636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63ba75848200'
down_revision: Union[str, Sequence[str], None] = 'bf751ea53a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_audio_seconds', sa.Float(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode_key', 'day', name='uq_usage_daily_user_mode_day')
    )
    op.create_index(op.f('ix_usage_daily_day'), 'usage_daily', ['day'], unique=False)
    op.create_index(op.f('ix_usage_daily_mode_key'), 'usage_daily', ['mode_key'], unique=False)
    op.create_index(op.f('ix_usage_daily_user_id'), 'usage_daily', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_daily_user_id'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_mode_key'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_day'), table_name='usage_daily')
    op.drop_table('usage_daily')
    # ### end Alembic commands ###
