"""mode_overrides

Revision ID: bf751ea53a90
Revises: c16bc38a51d5
Create Date: 2026-06-05 23:28:34.205089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf751ea53a90'
down_revision: Union[str, Sequence[str], None] = 'c16bc38a51d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_online_llm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode_key', name='uq_mode_overrides_user_mode')
    )
    op.create_index(op.f('ix_mode_overrides_mode_key'), 'mode_overrides', ['mode_key'], unique=False)
    op.create_index(op.f('ix_mode_overrides_user_id'), 'mode_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mode_overrides_user_id'), table_name='mode_overrides')
    op.drop_index(op.f('ix_mode_overrides_mode_key'), table_name='mode_overrides')
    op.drop_table('mode_overrides')
    # ### end Alembic commands ###
