"""provider_keys

Revision ID: c16bc38a51d5
Revises: cbd646481059
Create Date: 2026-06-05 07:48:11.434966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c16bc38a51d5'
down_revision: Union[str, Sequence[str], None] = 'cbd646481059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ciphertext', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_keys_user_provider')
    )
    op.create_index(op.f('ix_provider_keys_provider'), 'provider_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_keys_user_id'), 'provider_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_keys_user_id'), table_name='provider_keys')
    op.drop_index(op.f('ix_provider_keys_provider'), table_name='provider_keys')
    op.drop_table('provider_keys')
    # ### end Alembic commands ###
